//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huellitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Facturas = new HashSet<Factura>();
            this.Vacunacions = new HashSet<Vacunacion>();
        }
    
        public int IdCita { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Tipo { get; set; }
        public int IdVeterinaria { get; set; }
        public int IdMascota { get; set; }
        public string IdEmpleadoVet { get; set; }
        public string MotivoConsulta { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> PesoKg { get; set; }
        public Nullable<decimal> TemperaturaC { get; set; }
        public string Diagnostico { get; set; }
        public string TratamientoRecomendado { get; set; }
        public string NotasAdicionales { get; set; }
        public Nullable<System.DateTime> ProximaCitaFecha { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Veterinaria Veterinaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacunacion> Vacunacions { get; set; }
    }
}
