//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huellitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.FacturaDetalles = new HashSet<FacturaDetalle>();
        }
    
        public int IdFactura { get; set; }
        public string NumeroFactura { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public decimal Total { get; set; }
        public string CedulaUsuario { get; set; }
        public string IdEmpleadoCaja { get; set; }
        public Nullable<int> IdCita { get; set; }
        public string Estado { get; set; }
        public string Notas { get; set; }
        public Nullable<int> IdMetodoPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string ReferenciaPago { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturaDetalles { get; set; }
    }
}
