//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huellitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialMedico
    {
        public int IdCambio { get; set; }
        public int IdMascota { get; set; }
        public int IdEnfermedadPrevia { get; set; }
        public Nullable<int> IdOperacion { get; set; }
        public Nullable<int> IdVacunacion { get; set; }
        public string TratamientoRecomendado { get; set; }
        public string Notas { get; set; }
    
        public virtual EnfermedadPrevia EnfermedadPrevia { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Operacion Operacion { get; set; }
        public virtual Vacunacion Vacunacion { get; set; }
    }
}
