//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huellitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialCambio
    {
        public int IdCambio { get; set; }
        public System.DateTime FechaHoraCambio { get; set; }
        public string IdEmpleadoResponsable { get; set; }
        public string TablaAfectada { get; set; }
        public string RegistroAfectadoID { get; set; }
        public string DetalleCambio { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
