//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huellitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int IdInventario { get; set; }
        public int IdMedicamento { get; set; }
        public int IdVeterinaria { get; set; }
        public int CantidadDisponible { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaActualizacion { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Veterinaria Veterinaria { get; set; }
    }
}
